default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  port: 8080

development:
  <<: *default
  database: library_development

test:
  <<: *default
  database: library_test

production:
  <<: *default
  database: library_production